---
- name: Setup Android-x86 on QEMU VM with ADB and VNC access
  hosts: localhost
  become: true
  tasks:
    # Step 1: Install required packages
    - name: Install necessary tools for QEMU and Android setup
      apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - android-tools-adb
          - wget
        state: present
        update_cache: yes

    # Step 2: Define variables for download and setup
    - name: Set variables
      set_fact:
        iso_url: "https://osdn.net/projects/android-x86/releases/download/69249/android-x86_64-9.0-r2.iso"
        iso_file: "/tmp/android-x86_64-9.0-r2.iso"
        disk_image: "/tmp/android.img"
        disk_size: "75G"
        memory: "4096"
        cpu: "1"
        vnc_apk: "droidVNC-NG-1.2.0.apk"
        vnc_apk_url: "https://github.com/bk138/droidVNC-NG/releases/download/v1.2.0/{{ vnc_apk }}"

    # Step 3: Download Android-x86 ISO
    - name: Download Android-x86 ISO
      get_url:
        url: "{{ iso_url }}"
        dest: "{{ iso_file }}"
        mode: '0644'
      register: iso_download
      retries: 3
      delay: 10
      until: iso_download is succeeded

    # Step 4: Create a QEMU disk image
    - name: Create QEMU disk image for Android-x86
      command: "qemu-img create -f qcow2 {{ disk_image }} {{ disk_size }}"

    # Step 5: Start the QEMU VM for installation
    - name: Start QEMU VM for installation (User will install Android-x86 manually)
      command: >
        qemu-system-x86_64
        -enable-kvm
        -m {{ memory }}
        -smp {{ cpu }}
        -hda {{ disk_image }}
        -cdrom {{ iso_file }}
        -boot d
        -vga std
        -usb
        -device usb-tablet
      async: 1200  # Allow user 20 minutes to install the OS
      poll: 0

    # Step 6: Wait for user to install and reboot
    - name: Prompt user to complete installation and reboot
      pause:
        prompt: "Press Enter after completing the Android-x86 installation and rebooting the VM"

    # Step 7: Start the QEMU VM with port redirection for ADB
    - name: Start QEMU VM with ADB access
      command: >
        qemu-system-x86_64
        -enable-kvm
        -m {{ memory }}
        -smp {{ cpu }}
        -hda {{ disk_image }}
        -vga std
        -usb
        -device usb-tablet
        -redir tcp:5555::5555
      async: 120
      poll: 0

    # Step 8: Wait for VM to boot
    - name: Wait for the VM to boot
      pause:
        seconds: 60

    # Step 9: Connect via ADB
    - name: Connect to the VM via ADB
      command: "adb connect localhost:5555"

    # Step 10: Enable root access via ADB
    - name: Enable root access on the Android VM
      command: "adb root"

    # Step 11: Download the VNC server APK
    - name: Download VNC server APK
      get_url:
        url: "{{ vnc_apk_url }}"
        dest: "/tmp/{{ vnc_apk }}"
        mode: '0644'

    # Step 12: Install the VNC server APK on Android-x86
    - name: Install VNC server APK on Android VM
      command: "adb install /tmp/{{ vnc_apk }}"

    # Step 13: Start the VNC server on Android-x86
    - name: Start the VNC server on the Android VM
      command: "adb shell am start -n com.bk138.droidvncng/.DroidVNC"

    # Step 14: Display VNC connection instructions
    - name: VNC server running instructions
      debug:
        msg: "Android-x86 is now installed. Connect via ADB on port 5555 and VNC using a VNC client."
